export const ActionTypes = {
  TOGGLE_FAVOURITE: 'TOGGLE_FAVOURITE',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  SET_PHOTOS: 'SET_PHOTOS',
  SET_TOPICS: 'SET_TOPICS',
  SET_ERROR: 'SET_ERROR',
  SET_PHOTOS_BY_TOPIC: 'SET_PHOTOS_BY_TOPIC',
};